<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204124632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, food_type VARCHAR(50) NOT NULL, calories_total DOUBLE PRECISION NOT NULL, proteines_g DOUBLE PRECISION NOT NULL, carbohidrates_g DOUBLE PRECISION NOT NULL, fats_g DOUBLE PRECISION NOT NULL, url_image VARCHAR(255) DEFAULT NULL, bar_scanner BOOLEAN NOT NULL, register_method VARCHAR(50) NOT NULL, register_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE meal');
    }
}
