<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204132657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, muscular_group VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, technique TEXT DEFAULT NULL, url_image VARCHAR(255) DEFAULT NULL, url_video VARCHAR(255) DEFAULT NULL, necessary_material VARCHAR(255) DEFAULT NULL, difficulty VARCHAR(50) NOT NULL, compound BOOLEAN NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE exercise');
    }
}
