<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421194440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE achievement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(100) NOT NULL, otorgated_xp INT NOT NULL, url_icon VARCHAR(255) DEFAULT NULL, judgment VARCHAR(255) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, muscular_group VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, technique TEXT DEFAULT NULL, url_image VARCHAR(255) DEFAULT NULL, url_video VARCHAR(255) DEFAULT NULL, necessary_material VARCHAR(255) DEFAULT NULL, difficulty VARCHAR(50) NOT NULL, compound BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise_training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_week INT NOT NULL, order_rutine INT NOT NULL, series_objective INT NOT NULL, reps_min INT NOT NULL, reps_max INT NOT NULL, rest_seconds INT NOT NULL, notes TEXT DEFAULT NULL, routine_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D37E2A67F27A94C7 ON exercise_training (routine_id)');
        $this->addSql('CREATE INDEX IDX_D37E2A67E934951A ON exercise_training (exercise_id)');
        $this->addSql('CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bar_scanner VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, calories_by_100 DOUBLE PRECISION NOT NULL, proteine_by_100 DOUBLE PRECISION NOT NULL, carbohidrates_by_100 DOUBLE PRECISION NOT NULL, fats_by_100 DOUBLE PRECISION NOT NULL, fiber_by_100 DOUBLE PRECISION NOT NULL, font VARCHAR(255) DEFAULT NULL, category VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE food_allergen (food_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY (food_id, allergen_id))');
        $this->addSql('CREATE INDEX IDX_DF22F8CBA8E87C4 ON food_allergen (food_id)');
        $this->addSql('CREATE INDEX IDX_DF22F8C6E775A4A ON food_allergen (allergen_id)');
        $this->addSql('CREATE TABLE meal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, food_type VARCHAR(50) NOT NULL, calories_total DOUBLE PRECISION NOT NULL, proteines_g DOUBLE PRECISION NOT NULL, carbohidrates_g DOUBLE PRECISION NOT NULL, fats_g DOUBLE PRECISION NOT NULL, url_image VARCHAR(255) DEFAULT NULL, bar_scanner BOOLEAN NOT NULL, register_method VARCHAR(50) NOT NULL, register_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes TEXT DEFAULT NULL, app_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9EF68E9C4A3353D8 ON meal (app_user_id)');
        $this->addSql('CREATE TABLE meal_food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount_grams DOUBLE PRECISION NOT NULL, calories_calculated DOUBLE PRECISION NOT NULL, proteine_calculated DOUBLE PRECISION NOT NULL, carbohi_calculated DOUBLE PRECISION NOT NULL, fats_calculated DOUBLE PRECISION NOT NULL, meal_id INT NOT NULL, food_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CEE6FA03639666D6 ON meal_food (meal_id)');
        $this->addSql('CREATE INDEX IDX_CEE6FA03BA8E87C4 ON meal_food (food_id)');
        $this->addSql('CREATE TABLE plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, monthly_price DOUBLE PRECISION NOT NULL, access_ia_ilimitated BOOLEAN NOT NULL, advanced_rutines BOOLEAN NOT NULL, max_consult_ia_month INT NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE routine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, objective VARCHAR(100) NOT NULL, days_week INT NOT NULL, dispo_material VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BF6D8D67E3C61F9 ON routine (owner_id)');
        $this->addSql('CREATE TABLE routine_exercise (routine_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (routine_id, exercise_id))');
        $this->addSql('CREATE INDEX IDX_50CE302AF27A94C7 ON routine_exercise (routine_id)');
        $this->addSql('CREATE INDEX IDX_50CE302AE934951A ON routine_exercise (exercise_id)');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auto_renew BOOLEAN NOT NULL, payment_method VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3C664D3A76ED395 ON subscription (user_id)');
        $this->addSql('CREATE INDEX IDX_A3C664D3E899029B ON subscription (plan_id)');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_series INT NOT NULL, repetitions INT NOT NULL, weight DOUBLE PRECISION NOT NULL, duration_minutes INT NOT NULL, notes TEXT DEFAULT NULL, completed BOOLEAN NOT NULL, one_rm_estimated DOUBLE PRECISION DEFAULT NULL, app_user_id INT NOT NULL, exercise_id INT NOT NULL, routine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5128A8F4A3353D8 ON training (app_user_id)');
        $this->addSql('CREATE INDEX IDX_D5128A8FE934951A ON training (exercise_id)');
        $this->addSql('CREATE INDEX IDX_D5128A8FF27A94C7 ON training (routine_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(200) NOT NULL, password VARCHAR(200) NOT NULL, name VARCHAR(50) NOT NULL, lastname VARCHAR(255) NOT NULL, points_xp INT NOT NULL, continuity INT NOT NULL, level INT NOT NULL, rol VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, age INT DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, actual_weight DOUBLE PRECISION DEFAULT NULL, purpose VARCHAR(255) DEFAULT NULL, activity_level VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_allergen (user_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY (user_id, allergen_id))');
        $this->addSql('CREATE INDEX IDX_C532ECCEA76ED395 ON user_allergen (user_id)');
        $this->addSql('CREATE INDEX IDX_C532ECCE6E775A4A ON user_allergen (allergen_id)');
        $this->addSql('CREATE TABLE user_achievement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, achievement_name VARCHAR(255) NOT NULL, date_obtained TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notificated BOOLEAN NOT NULL, app_user_id INT NOT NULL, achievement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F68B6644A3353D8 ON user_achievement (app_user_id)');
        $this->addSql('CREATE INDEX IDX_3F68B664B3EC99FE ON user_achievement (achievement_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE exercise_training ADD CONSTRAINT FK_D37E2A67F27A94C7 FOREIGN KEY (routine_id) REFERENCES routine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_training ADD CONSTRAINT FK_D37E2A67E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE food_allergen ADD CONSTRAINT FK_DF22F8CBA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE food_allergen ADD CONSTRAINT FK_DF22F8C6E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meal ADD CONSTRAINT FK_9EF68E9C4A3353D8 FOREIGN KEY (app_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_food ADD CONSTRAINT FK_CEE6FA03639666D6 FOREIGN KEY (meal_id) REFERENCES meal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_food ADD CONSTRAINT FK_CEE6FA03BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE routine ADD CONSTRAINT FK_4BF6D8D67E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE routine_exercise ADD CONSTRAINT FK_50CE302AF27A94C7 FOREIGN KEY (routine_id) REFERENCES routine (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE routine_exercise ADD CONSTRAINT FK_50CE302AE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3E899029B FOREIGN KEY (plan_id) REFERENCES plan (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8F4A3353D8 FOREIGN KEY (app_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8FE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training ADD CONSTRAINT FK_D5128A8FF27A94C7 FOREIGN KEY (routine_id) REFERENCES routine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_allergen ADD CONSTRAINT FK_C532ECCEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_allergen ADD CONSTRAINT FK_C532ECCE6E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B6644A3353D8 FOREIGN KEY (app_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B664B3EC99FE FOREIGN KEY (achievement_id) REFERENCES achievement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_training DROP CONSTRAINT FK_D37E2A67F27A94C7');
        $this->addSql('ALTER TABLE exercise_training DROP CONSTRAINT FK_D37E2A67E934951A');
        $this->addSql('ALTER TABLE food_allergen DROP CONSTRAINT FK_DF22F8CBA8E87C4');
        $this->addSql('ALTER TABLE food_allergen DROP CONSTRAINT FK_DF22F8C6E775A4A');
        $this->addSql('ALTER TABLE meal DROP CONSTRAINT FK_9EF68E9C4A3353D8');
        $this->addSql('ALTER TABLE meal_food DROP CONSTRAINT FK_CEE6FA03639666D6');
        $this->addSql('ALTER TABLE meal_food DROP CONSTRAINT FK_CEE6FA03BA8E87C4');
        $this->addSql('ALTER TABLE routine DROP CONSTRAINT FK_4BF6D8D67E3C61F9');
        $this->addSql('ALTER TABLE routine_exercise DROP CONSTRAINT FK_50CE302AF27A94C7');
        $this->addSql('ALTER TABLE routine_exercise DROP CONSTRAINT FK_50CE302AE934951A');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3A76ED395');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3E899029B');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8F4A3353D8');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8FE934951A');
        $this->addSql('ALTER TABLE training DROP CONSTRAINT FK_D5128A8FF27A94C7');
        $this->addSql('ALTER TABLE user_allergen DROP CONSTRAINT FK_C532ECCEA76ED395');
        $this->addSql('ALTER TABLE user_allergen DROP CONSTRAINT FK_C532ECCE6E775A4A');
        $this->addSql('ALTER TABLE user_achievement DROP CONSTRAINT FK_3F68B6644A3353D8');
        $this->addSql('ALTER TABLE user_achievement DROP CONSTRAINT FK_3F68B664B3EC99FE');
        $this->addSql('DROP TABLE achievement');
        $this->addSql('DROP TABLE allergen');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_training');
        $this->addSql('DROP TABLE food');
        $this->addSql('DROP TABLE food_allergen');
        $this->addSql('DROP TABLE meal');
        $this->addSql('DROP TABLE meal_food');
        $this->addSql('DROP TABLE plan');
        $this->addSql('DROP TABLE routine');
        $this->addSql('DROP TABLE routine_exercise');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE training');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_allergen');
        $this->addSql('DROP TABLE user_achievement');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
