<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204130443 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bar_scanner VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, calories_by_100 DOUBLE PRECISION NOT NULL, proteine_by_100 DOUBLE PRECISION NOT NULL, carbohidrates_by_100 DOUBLE PRECISION NOT NULL, fats_by_100 DOUBLE PRECISION NOT NULL, fiber_by_100 DOUBLE PRECISION NOT NULL, font VARCHAR(255) DEFAULT NULL, category VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE food');
    }
}
