<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204125506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount_grams DOUBLE PRECISION NOT NULL, calories_calculated DOUBLE PRECISION NOT NULL, proteine_calculated DOUBLE PRECISION NOT NULL, carbohi_calculated DOUBLE PRECISION NOT NULL, fats_calculated DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE meal_food');
    }
}
