<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428153511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE data_backup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, file_size_bytes INT NOT NULL, backup_type VARCHAR(50) NOT NULL, include_personal_data BOOLEAN NOT NULL, include_routines BOOLEAN NOT NULL, include_trainings BOOLEAN NOT NULL, include_meals BOOLEAN NOT NULL, include_achievements BOOLEAN NOT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_automated BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5F0EE0B5A76ED395 ON data_backup (user_id)');
        $this->addSql('CREATE TABLE social_connection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, provider_id VARCHAR(255) NOT NULL, provider_email VARCHAR(255) DEFAULT NULL, provider_name VARCHAR(255) DEFAULT NULL, profile_picture_url VARCHAR(500) DEFAULT NULL, share_stats BOOLEAN NOT NULL, auto_post BOOLEAN NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_sync TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7A4C1A4A76ED395 ON social_connection (user_id)');
        $this->addSql('CREATE TABLE training_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, preferred_time VARCHAR(50) DEFAULT NULL, training_intensity VARCHAR(50) DEFAULT NULL, training_duration_minutes INT NOT NULL, rest_between_sets_seconds INT NOT NULL, notifications_enabled BOOLEAN NOT NULL, reminder_before_training BOOLEAN NOT NULL, reminder_minutes_before INT NOT NULL, sound_enabled BOOLEAN NOT NULL, measurement_unit VARCHAR(50) DEFAULT NULL, profile_public BOOLEAN NOT NULL, stats_visible BOOLEAN NOT NULL, achievements_visible BOOLEAN NOT NULL, routines_visible BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E7D70A35A76ED395 ON training_preference (user_id)');
        $this->addSql('ALTER TABLE data_backup ADD CONSTRAINT FK_5F0EE0B5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_connection ADD CONSTRAINT FK_E7A4C1A4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_preference ADD CONSTRAINT FK_E7D70A35A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE data_backup DROP CONSTRAINT FK_5F0EE0B5A76ED395');
        $this->addSql('ALTER TABLE social_connection DROP CONSTRAINT FK_E7A4C1A4A76ED395');
        $this->addSql('ALTER TABLE training_preference DROP CONSTRAINT FK_E7D70A35A76ED395');
        $this->addSql('DROP TABLE data_backup');
        $this->addSql('DROP TABLE social_connection');
        $this->addSql('DROP TABLE training_preference');
    }
}
